faces_folder: 'faces'
grant_access: ['Lee Ping', 'Andrew Ng', 'Geoffrey Hinton']
# if True, will use the more accurate but slower face detector
use_accurate_detector: True 
open_angle: 135
close_angle: 0

